# Generated by Django 3.1.1 on 2020-10-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
