# Generated by Django 3.1.1 on 2020-10-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201001_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='default-avatar.png', upload_to='avatar_photos/'),
        ),
    ]
