# Generated by Django 3.1.1 on 2020-10-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201002_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date',
        ),
    ]
