# Generated by Django 3.1.1 on 2020-10-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='picture',
            field=models.ImageField(blank=True, default='default-avatar.jpg', null=True, upload_to='avatar_photos/'),
        ),
    ]
